#!/bin/bash

clear screen

echo -e "adb-wireless v2.0 Copyright © 2018 Microsoft10 6-3-2018"

echo

# adb binary check
test_cmd() {
    if which "$1" &>/dev/null
    then
        true
    else
        echo "Error: cannot execute \"$1\", install either this '\"$2\"' or this '\"$3\"'">&2
        exit 2
    fi
}

test_cmd adb  adb android-tools-adb

clear screen

echo -e "adb-wireless v2.0 Copyright © 2018 Microsoft10 6-3-2018"

echo

# Script usage
echo -e "Usage:"
echo -e "Connect device with adb wirelessly via Wi-Fi"

echo

echo -e "Instructions:"
echo -e "1. Connect your device to your computer via USB"
echo -e "2. Make sure that USB debugging is enabled in [Device--> Settings--> Developer options]"
echo -e "3. Make sure that your computer and your device are connected to Wi-Fi or your Mobile Hotspot"

echo

echo -e "NOTE: This is mandatory. Before you connect your device with adb via Wi-Fi, you must connect it via USB to your computer first. Once adb is connected via Wi-Fi, you can remove the USB"

echo

read -p "Have you read the above instructions? If yes, press ENTER to continue..."

clear screen

echo -e "adb-wireless v2.0 Copyright © 2018 Microsoft10 6-3-2018"

# Mandatory, to prevent adb from refusing to connect to device
{
  adb tcpip 5555
} &> /dev/null

echo

echo -e "What is your device's IP address?"
echo -e "GNOME:"
echo -e "[Computer--> Network--> Gear icon--> You can choose either Default Route / DNS"
echo -e "Example: 192.168.43.224"
echo -e "Mandatory to input your own IP address or else it will fail to connect"
read -p ":" IP_ADDRESS

echo

if [ -z "$IP_ADDRESS" ]
then
    echo -e "Invalid input, quitting..."
    exit 1
fi

echo

echo -e "Connecting device via IP $IP_ADDRESS..."

# {
  adb connect $IP_ADDRESS
# } &> /dev/null

echo

read -p "Press ENTER to exit"

exit 0
